steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'me-central2-docker.pkg.dev/$PROJECT_ID/salam-builds/react-app:latest',
        '.'
      ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'me-central2-docker.pkg.dev/$PROJECT_ID/salam-builds/react-app:latest'
      ]

images:
  - 'me-central2-docker.pkg.dev/$PROJECT_ID/salam-builds/react-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
