substitutions:
  _VM_NAME: "gcp-stg-app-01"
  _VM_ZONE: "me-central2-c"
  _IMAGE_NAME: "me-central2-docker.pkg.dev/$PROJECT_ID/salam-builds/react-app"

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_IMAGE_NAME:$SHORT_SHA',
        '-t',
        '$_IMAGE_NAME:latest',
        '.'
      ]

  # Step 2: Push the images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME:latest']

  # Step 3: SSH into VM and deploy with docker-compose
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo ">>> Connecting to VM: $_VM_NAME in $_VM_ZONE"
        gcloud compute ssh $_VM_NAME --zone $_VM_ZONE --tunnel-through-iap --command "
          mkdir -p ~/deploy && cd ~/deploy
          echo '>>> Writing docker-compose.yml'
          cat > docker-compose.yml <<EOF
          version: '3.8'
          services:
            react-app:
              image: $_IMAGE_NAME:latest
              ports:
                - '8080:8080'
              restart: unless-stopped
          EOF
          echo '>>> Pulling latest image'
          docker compose pull
          echo '>>> Restarting app'
          docker compose up -d --remove-orphans
          echo '>>> Running containers'
          docker ps
        "

images:
  - '$_IMAGE_NAME:$SHORT_SHA'
  - '$_IMAGE_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY
